### ISSUE TITLE
fox local dependency

### ISSUE THREAD

**Issue by peteshand** [LogicInteractive/xUnreal#1]
Hey, total note that the readme says in Caps that this plugin is in development and not ready for use, but would it be possible to include the local dependency that are in build.hxml

```
-cp c:/dev/fox/fox/hx
-cp c:/dev/fox/thirdparty/common
```

**Comment by datee** [comment]
Hm, you are correct - there is a connection to this local dependency.. Its part of a larger library i cant put online right now, but im planning to remove this dependency very soon!

For now, i think it can be just removed - as there should be no places the library is really used.

**Comment by peteshand** [comment]
Oh yep, just commenting out references to those libs resolved things..
Seems to work quite well.. nice work!
